#!/bin/bash

# Exit on error
set -e

echo "Initializing Terraform..."
terraform init

echo "Planning deployment..."
terraform plan -out=tfplan

echo "Applying Terraform plan..."
terraform apply tfplan

